"""Build the paste-ready Solution Writeup: metadata header + verbatim body.

Kept as a script so the pasted body can never drift from the source writeup, AND so the
header's own claims cannot go stale: the word count is computed from the body, and the
test-suite count is counted from disk. Both were hardcoded once and had already drifted
(the header still said 1390 words and 4 test suites when the body was 1499 words and
there were 9 suites) -- a writeup that misstates its own numbers is exactly the kind of
small inaccuracy that undermines an otherwise honest paper.
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "NEURAL_SOLUTION_WRITEUP.md")
DST = os.path.join(HERE, "NEURAL_WRITEUP_PASTE_READY.md")
SOLVER_DIR = os.path.join(os.path.dirname(HERE), "solver")

FENCE = re.compile(r"```.*?```", re.S)
TABLE = re.compile(r"^\s*\|.*\|\s*$", re.M)
URL = re.compile(r"https?://\S+")
WORD = re.compile(r"[A-Za-z0-9][A-Za-z0-9'\-]*")


def prose_words(text: str) -> int:
    return len(WORD.findall(URL.sub(" ", TABLE.sub(" ", FENCE.sub(" ", text)))))


def count_test_files() -> int:
    """Test files that actually exist, so the header cannot over- or under-claim."""
    if not os.path.isdir(SOLVER_DIR):
        return 0
    n = sum(1 for f in os.listdir(SOLVER_DIR)
            if f.startswith("test_") and f.endswith(".py"))
    # the submission gate lives one level up, next to the workspace
    parent = os.path.dirname(HERE)
    for candidate in ("test_submit_gate.py",):
        if os.path.isfile(os.path.join(parent, candidate)):
            n += 1
    return n


body = open(SRC, encoding="utf-8").read()
words = prose_words(body)
suites = count_test_files()

HEADER = f"""# Paste-ready: ARC-AGI-2 Solution Writeup

> 直接整段粘贴到 Kaggle Writeup 编辑器即可，正文无需改动。
>
> **Title**
> A Licence-Clean Test-Time-Training Solver for ARC-AGI-2, and Why the Symbolic Floor Is Exactly Zero
>
> **Subtitle**
> Coverage, not search, is the binding constraint: we measure the symbolic floor at exactly 0/120, the fallback layer at exactly 0, and a licence-clean LoRA test-time-training pipeline at {100.0 * 1 / 24:.2f}% with 100% candidate coverage.
>
> **Track**
> ARC-AGI-2 Solution Writeup (companion to the Paper Track diagnostic
> *"When Cheap Transformations Vanish"*). Word count of the body below: {words} (limit 1500).
>
> **Project Links — required by the rules**
> - Public notebook (this is the code submission and the notebook Kaggle re-runs):
>   https://www.kaggle.com/code/luoguoqiang/arc26-submit-full
> - Version 1 of that notebook is the submitted version.
> - Open-source repository (MIT-0):
>   https://github.com/LuoGuoQiang-web/arc-prize-2026-arc-agi-2-v1
> - The neural pipeline lives in `neural/` of that repository: the solver, {suites} test
>   suites, the Kaggle GPU recipe, the submission gate, and the experiment ledger.
>
> **Media Gallery**
> 1. `cover.png` — cover image. **Required by the rules**, not decorative.
> 2. `attempt_breakdown.png` — this writeup's own evidence figure, generated by
>    `figures/make_degeneracy_figure.py`. Every number drawn in it is re-derived from the
>    run artifacts by `figures/verify_figure.py`, so it cannot silently misstate the data.
>
> **Do NOT attach `coverage_curve.png` here.** That figure is the evidence figure for the
> companion Paper Track diagnostic; this writeup does not discuss that curve. (The
> Paper Track paste-ready file asks for both images, which is correct for *that* entry.)
>
> **Checklist before pressing Submit**
> - [ ] Pasted the body below (everything from the first `#` heading onward)
> - [ ] Cover image uploaded
> - [ ] `attempt_breakdown.png` uploaded as the evidence figure
> - [ ] Public notebook linked
> - [ ] Code submission linked (run `update_submission_ref.py` FIRST -- the ref currently
>       cited in the Paper Track file was a rejected submission)
> - [ ] Repository link present

---

"""

with open(DST, "w", encoding="utf-8") as fh:
    fh.write(HEADER + body)

print(f"wrote {DST}")
print(f"  body: {len(body)} chars, prose words = {words} (limit 1500)")
print(f"  test suites counted on disk: {suites}")
print(f"  total file: {os.path.getsize(DST)} bytes")
if words > 1500:
    raise SystemExit(f"ABORT: body is {words} words, over the 1500 limit")

